ping_pong/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
]

ping_pong/ping_pong/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path("", index, name="index"),
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
]

ping_pong/score/models.py
from django.db import models
from django.contrib.auth.models import User


class Score(models.Model):
    name = models.CharField(max_length=255)
    # score = models.IntegerField()

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=255)
    score = models.IntegerField()
    is_won = models.BooleanField(default=False)
    played_at = models.DateTimeField(auto_now_add=True)
    played_by = models.ForeignKey(User, related_name="game", on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatar_images", blank=True, null=True)


# Create your models here.

ping_pong/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username to play",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username to play",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email address",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat Password",
                "class": "w-full py-4 px-5 rounded-xl",
            }
        )
    )

ping_pong/core/views.py
from django.shortcuts import render, redirect
from score.models import Score, Game
from .forms import SignUpForm


def index(request):
    games = Game.objects.all()
    return render(
        request,
        "core/index.html",
        {
            "games": games,
        },
    )


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect("/login/")
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {"form": form})

ping_pong/core/templates/core/game.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <script src="script.js" type="module"></script>
    <title>Document</title>
</head>

<body>
    <div class="playerName">
        <div id="player1Name">Player 1</div>
        <div id="player2Name">Player 2</div>

    </div>
    <div class="score">
        <div id="player-score">0</div>
        <div id="computer-score">0</div>
    </div>
    <div class="ball" id="ball"></div>
    <div class="paddle left" id="player-paddle"></div>
    <div class="paddle right" id="computer-paddle"></div>


</body>

</html>

ping_pong/core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>Ping Pong Game</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 50px;
        }

        header {
            background-color: #f2f2f2;
            padding: 20px;
            border-radius: 10px;
        }

        #play-link {
            display: inline-block;
            padding: 10px 20px;
            font-size: 18px;
            text-decoration: none;
            background-color: #4caf50;
            color: #fff;
            border-radius: 5px;
        }

        #play-link:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <header>
        <h1>Welcome to the Ping Pong Game!</h1>
    </header>

    <section>
        <p>
            FT_TRANCENDENCE. Click the button below to start playing.
        </p>

        <a id="play-link" href="{% url 'core:login' %}">Log in</a>
        <a id="play-link" href="{% url 'core:signup' %}">Sign up</a>

    </section>
</body>

</html>

ping_pong/core/templates/core/signup.html
<!DOCTYPE html>
<html>

<head>
    <title>Sign Up</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body class="bg-gray-100">

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">

        <h2 class="mb-6 text-3xl">Sign Up</h2>

        <form method="post" actio=".">

            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username}}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email}}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1}}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2}}
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                {{ field.errors }}
                {%endfor%}
                {{ form.non_field_errors }}


            </div>
            {% endif %}



            <button class="w-full bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600">Sign Up</button>

        </form>

    </div>

</body>

</html>